# Use the latest Ubuntu image as the base image
From ubuntu:latest

# Update the APT package index and upgrade installed packages
Run apt-get update && apt-get upgrade -y

# Define the command to run when the container starts
CMD echo "Hello, World!"
